### PR TITLE
Support specifying classpath for additional velocity tool classes

### PR DESCRIPTION
**Pull request by crtlib**
Hi. Needed this for instantiating some custom non-published velocity tool classes. Would be great to have it released soon 🙏

### CODE REVIEW

**Comment by davidmc24** [comment]
Thanks for the PR. I'm open to this change, but don't want to break compatibility for it. If you resolve that issue with test coverage to prove compatibility, I should be able to merge and release relatively soon afterward.

**Comment by crtlib** [comment]
Thanks, David. Indeed, my change broke the `supports configuring velocity tool classes` in `OptionsFunctionalSpec`. I just forced-pushed a change, so that we now specify the parent classloader in our custom one. Does it mean that the current tests already cover the needed compatibility? If not, can you please elaborate on what kind of test you have in mind? Thank you!

**Comment by davidmc24** [comment]
Yes, I'd thought that there was coverage for additional velocity tools. I try pretty hard not to add features without test coverage. If it failed before and passes now, that's probably good enough. We'll just need test coverage for the new case, where the classpath is configured (if you haven't added that already)

**Comment by crtlib** [comment]
Hi, David. Looks like I've managed to deliver a test for the new property 😅 Please take a look 🙏

**Review by davidmc24 — APPROVED** [review]

**Comment by crtlib** [comment]
@davidmc24 Thanks a lot 🙏

**Comment by davidmc24** [comment]
@crtlib Looks like the new test (and maybe functionality) isn't Windows compatible.  Mind trying for a fix?

https://github.com/davidmc24/gradle-avro-plugin/actions/runs/4055083756/jobs/6977738565

**Comment by crtlib** [comment]
@davidmc24 Sure, David. I'll give a try.

**Comment by crtlib** [comment]
@davidmc24 Here it is: https://github.com/crtlib/gradle-avro-plugin/commit/e778f213c3913738c223ea2e934e4ae354f7ff27. Should I create a PR or you'll just cherry-pick?

**Comment by davidmc24** [comment]
PR if possible, please

**Comment by davidmc24** [comment]
@crtlib Release underway.  Once https://github.com/davidmc24/gradle-avro-plugin/actions/runs/4104821988 completes, it should be published to Maven Central as version 1.6.0.

**Comment by davidmc24** [comment]
Released

**Pull request merged**
