### PR TITLE
Upgrade to Gradle Wrapper 7.0.2

### PR DESCRIPTION
**Pull request by izeye**
This PR upgrades to Gradle Wrapper 7.0.2.

### CODE REVIEW

**Comment by davidmc24** [comment]
Thank you for the pull request. Was the previous version of the wrapper breaking for you, or is there some feature in the new version you were looking to leverage?

**Comment by izeye** [comment]
@davidmc24 Thanks for the feedback! I just noticed that the RC version is being used and created this to make this project build on the latest GC version.

**Comment by tilscarvalho** [comment]
ok

**Comment by robvadai** [comment]
Using Maven Central and latest version 1.2.0 works - thanks

**Pull request closed without merging**
